info:
  contact: {}
paths:
  /user/create:
    post:
      consumes:
      - multipart/form-data
      description: 增加用户信息
      operationId: /user/create
      parameters:
      - description: name
        in: formData
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: 用户信息
      tags:
      - 用户信息接口
  /user/index:
    get:
      consumes:
      - application/json
      description: 获取用户信息
      operationId: /user/index
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: 用户信息
      tags:
      - 用户信息接口
swagger: "2.0"
